name: Build apk on feature merge

on:
  push:
    branches:
      - main

jobs:
  apk:
    name: Build Android App
    uses: sparkfabrik/android-build-action/action.yml@master
    with:
      project-path: android
      output-path: my-app.apk
