name: Build apk on feature merge

on:
  push:
    branches:
      - main

jobs:
  apk:
    name: Build Android App
    uses: sparkfabrik/android-build-action@v1.2.0
    with:
      project-path: android
      output-path: my-app.apk
